### ISSUE TITLE
三个无效的方法

### ISSUE THREAD

**Issue by git-lt** [vvpvvp/manba#2]
```javascript
manba().isThisYear()
manba().isBefore()
manba().isAfter()
```
这三个API 是不是没有写完？

**Comment by vvpvvp** [comment]
并没有这三个api啊？
其实可以通过distance这个方法来完成这三个判断。
manba().distance('2018-01-01', manba.YEAR)
manba().distance('2018-01-01', manba.DAY)
manba().distance('2018-01-01', manba.DAY)
