### ISSUE TITLE
提最后一个BUG了，正则有误

### ISSUE THREAD

**Issue by git-lt** [vvpvvp/manba#3]
第 344 行，正则有误，会导致 这两个用例报错

manba("20141203").format("f") //2014-12-03 00:00:00
manba("201412031223").format("f") //2014-12-03 12:23:00

```
var aspNetJsonRegex = /^(\d{4,})\-(\d{2})\-(\d{2})\s?\:?(\d{2})?\:?(\d{2})?\:?(\d{2})?$/i;
```
应该是

```
/^(\d{4})\-?(\d{2})\-?(\d{2})\s?\:?(\d{2})?\:?(\d{2})?\:?(\d{2})?$/i
```
(文档页面的manba.js应该是之前es6构建出来的，是正确的，es5的版本不对)

然后原型里每个方法之前都去判断了日期是否合法，建议放到构造器中验证

完 ~~~

**Comment by vvpvvp** [comment]
不好意思，我忘记更新文档了。
manba("20141203").format("f")
这个方法目前不支持了，因为这种识别方式会给其他的类型造成混乱。
