### ISSUE TITLE
不能正确处理以秒为单位的时间戳

### ISSUE THREAD

**Issue by UnableRegister** [vvpvvp/manba#4]
manba(1459235037).format() 的实际返回结果为 1970-01-18，而文档中 manba(1459235037).format() 的返回结果为 2016-03-29。

源文件中第292行代码被注释
```
if (Utils.isNumber(arg1)) {
    // if (arg1 < 9999999999) arg1 = arg1 * 1000;
}
```
为什么呢？ #

**Comment by vvpvvp** [comment]
因为后期需要支持1970年以前的日期， 比如说 0010-10-10。
后期开发heyui组件库中的日期选择组件后，很多人手写日期，会有1000年之类的日期，如果使用上面那行代码，那对于1970年以前的日期的时间戳就会判断失败。

**Comment by vvpvvp** [comment]
文档有误，我更正一下。
